### ISSUE TITLE
Provider add A-records with error.  

### ISSUE THREAD

**Issue by DodgeCamaro** [barneyparker/terraform-provider-gd#1]
When I created new resources I had this error:
gd_record.clever: json: cannot unmarshal object into Go value of type []main.DnsRecord

Sometimes I had this error but new records were added.

**Comment by barneyparker** [comment]
That's an interesting error!  Do you have some example code which is causing this error?

**Comment by DodgeCamaro** [comment]
This is my provider.tf
`provider "gd" {
  key = ""
  secret = ""
}`

I'm used tfvars. And split subdomains to three files.

For example how I created new records

`resource "gd_record" "apk" {
  domain = "${var.domain}"
  type = "A"
  name = "apk"
  data = "${var.ip}"
  priority = 0
  ttl = 3600
}`

**Comment by DodgeCamaro** [comment]
@barneyparker What info do you need?
